[package]
name = "bst-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "0.4", default-feature = false }

[features]
default = ["std"]
std = ["num/std"]
